### ISSUE TITLE
The Docker image doesn't work out of the box

### ISSUE THREAD

**Issue by rht** [pelith/node-eauth-server#19]
These are the steps I had to do to make the Eauth on Docker work:
- Did `docker-compose up -d`
- Since the seed inside the node-eauth-server container is not set up, I had to
  modify components/seeders/20190725062038-oauth_clients.js to contain my
  client_id, client_secret, and redirect_uri
- Did `npx sequelize-cli db:seed:all` because `npx sequelize db:seed:all`
  (without -cli) said "command not found". But this resulted in `ERROR: Cannot
  find "/usr/src/app/config/config.json". Have you run "sequelize init"?`, so I
  did `npx sequelize-cli init` instead
- `npx sequelize-cli init` generated a sample config/config.js file, but this
  needs to be *manually* configured with my MySQL username, password, database
  name, host, which I already provided in the eauth-vars.env file above.
  Note that I don't actually have to run the `sequelize-cli init`; I just need
  to prepare the config/config.js
- Reran `npx sequelize-cli db:seed:all`. This resulted and error because the
  table `oauth_clients` doesn't exist. We fix that in the next step.
- Ran `docker exec -it my_container pkill node`. This restarted the node
  server, and triggered the DB tables creation.
- Ran `npx sequelize-cli db:seed:all`

After these steps, the Eauth is authenticating smoothly.

This is my relevant docker-compose.yml config:
```
  eauth:
    image: pelith/node-eauth-server:latest
    restart: always
    env_file:
      - eauth-vars.env
    ports:
      - 8080:8080
    links:
      - database
    volumes:
      - ./aqua/eauth_seed.js:/usr/src/app/components/seeders/20190725062038-oauth_clients.js
      - ./aqua/eauth_config.json:/usr/src/app/config/config.json
    depends_on:
      - database
```
Notice that I mounted the seed js and the config/config.json to automate the editing of the process. But ideally these could be made as parameters that are fed into the container.

cc: @hung-pelith
